import { ethers, raw } from "./rpc.mjs";
import fs from "node:fs";
const rabi = JSON.parse(fs.readFileSync("router/_abi.json","utf8"));
const fabi = JSON.parse(fs.readFileSync("factory/_abi.json","utf8"));
const ri = new ethers.Interface(rabi), fi = new ethers.Interface(fabi);
const bc = JSON.parse(fs.readFileSync("site/eth_bytecode.json","utf8")).contracts;
const GF = "0xB012e4A8F2c5FC4E8E4faCA9D5Ad6FfF13FBA887", ROUTER = "0x8622DD5bAb44185f2A458ac90384Ac99248f8d56", IMPL = "0x487E8A196812fEC534f2D2514bfdc7c609EBAe35";
const IMPL_HASH = "0x4013d721f43d3061e4593c5da8e1dfa64a943573240c7e247905c3a1986dbbec", RELEASE = "0xfe914882521999a177d69b49f021a265b39c3ae27fb1f89c29ae826a0d7bde4a";
const h = (s) => ethers.keccak256(ethers.toUtf8Bytes(s));
const NS = h("programmable.module-foundation.ethereum-graph.v1"), TOPO = h("engine-token-hook.v1"), NONCE_ID = h("programmable.module-foundation.ethereum-graph-nonce.v1"), LID = h("programmable.module-foundation.ethereum-launch-id.v1");
const TARGET_SALT_TYPEHASH = h("ProgrammableCreate2GraphTargetSaltV1(uint256 chainId,address factory,bytes32 routeNamespace,bytes32 routeNonce,bytes32 targetIdHash,bytes32 applicantSalt,address authorizedLauncher)");
const abi = ethers.AbiCoder.defaultAbiCoder();
const salt = (nonce, idHash, applicant) => ethers.keccak256(abi.encode(["bytes32","uint256","address","bytes32","bytes32","bytes32","bytes32","address"], [TARGET_SALT_TYPEHASH, 1, GF, NS, nonce, idHash, applicant, ROUTER]));
const M = "tuple(string name,string symbol,string description,string imageURI,string website,bytes socialData)";
const MS = "tuple(address factory,bytes32 factoryCodeHash,bytes32 moduleCodeHash,bytes32 descriptorHash,bytes configuration,uint16 creatorShareBps)[]";
const ROUTE = "tuple(bytes32 routeNamespace,bytes32 routeNonce,bytes32 topologyHash,bytes32 graphCommitment,tuple(bytes32 targetIdHash,bytes32 applicantSalt,uint256 deploymentValue,uint256 initializerValue,bytes initCode,bytes initializerCalldata)[] targets,tuple(uint8 targetIndex,bytes32 targetIdHash,address account,bytes32 runtimeCodeHash)[] expectedOutputs,bytes32 expectedGraphDeploymentHash)";
const txh = process.argv[2] || "0xfc044cf4223215ca8565b1d1c0104572fda58c1db9251dedc6b1dc8873b9372e";
const tx = await raw("eth_getTransactionByHash", [txh]);
const d = ri.parseTransaction({ data: tx.input, value: tx.value });
const permit = d.args.permit, sr = d.args.stampRequest;
console.log("permit", { launchWallet: permit.launchWallet, kind: Number(permit.kind), validAfter: Number(permit.validAfter), deadline: Number(permit.deadline), window_s: Number(permit.deadline - permit.validAfter), value: permit.value.toString(), nonce: permit.nonce });
console.log("stamp launchId", sr.launchId, "token", sr.token, "poolKey", { c0: sr.poolKey.currency0, c1: sr.poolKey.currency1, fee: Number(sr.poolKey.fee), ts: Number(sr.poolKey.tickSpacing), hooks: sr.poolKey.hooks });
console.log("signature len", (d.args.signature.length-2)/2);
const [route] = abi.decode([ROUTE], d.args.routePayload);
console.log("route ns ok", route.routeNamespace === NS, "topology ok", route.topologyHash === TOPO, "targets", route.targets.length);
const [eng, tok, hk] = route.targets;
console.log("target ids", eng.targetIdHash === h("engine"), tok.targetIdHash === h("token"), hk.targetIdHash === h("hook"), "applicant salts", eng.applicantSalt, tok.applicantSalt, hk.applicantSalt);
console.log("engine init value (ETH)", ethers.formatEther(eng.initializerValue), "deploymentValues", eng.deploymentValue.toString(), tok.deploymentValue.toString(), hk.deploymentValue.toString());
// decode initializer calldata
const init = fi.parseTransaction({ data: eng.initializerCalldata });
const p = init.args.p;
console.log("initializeGraph token", init.args.token, "hook", init.args.hook, "fundingPath", init.args.fundingPath);
console.log("params", { name: p.metadata.name, symbol: p.metadata.symbol, quote: p.quote, quoteDecimals: Number(p.quoteDecimals), initialTick: Number(p.initialTick), creatorBuyFeeBps: Number(p.creatorBuyFeeBps), creatorSellFeeBps: Number(p.creatorSellFeeBps), additionalQuoteAmount: p.additionalQuoteAmount.toString(), initialBuyQuoteAmount: p.initialBuyQuoteAmount.toString(), initialBuyMinimumTokenAmount: p.initialBuyMinimumTokenAmount.toString(), deadline: Number(p.deadline), tokenSalt: p.tokenSalt, hookSalt: p.hookSalt, modules: p.modules.length, social: ethers.toUtf8String(p.metadata.socialData) });
// recompute
const account = permit.launchWallet;
const nonce = ethers.keccak256(abi.encode(["bytes32","uint256","address","bytes32","address","bytes32"], [NONCE_ID, 1, IMPL, RELEASE, account, p.tokenSalt]));
console.log("routeNonce ok", nonce === route.routeNonce, "permit.nonce == routeNonce", permit.nonce === route.routeNonce);
const engInit = ethers.concat([bc.FoundationEthereumGraphProxyV1.creationBytecode, abi.encode(["address","bytes32","address"], [IMPL, IMPL_HASH, account])]);
console.log("engine initCode matches tx", ethers.keccak256(engInit) === ethers.keccak256(eng.initCode));
const engine = ethers.getCreate2Address(GF, salt(nonce, h("engine"), ethers.ZeroHash), ethers.keccak256(engInit));
const tokInit = ethers.concat([bc.FoundationTokenV1.creationBytecode, abi.encode([M, "address"], [p.metadata, engine])]);
console.log("token initCode matches tx", ethers.keccak256(tokInit) === ethers.keccak256(tok.initCode));
const token = ethers.getCreate2Address(GF, salt(nonce, h("token"), ethers.ZeroHash), ethers.keccak256(tokInit));
const hookInit = ethers.concat([bc.FoundationHookV2.creationBytecode, abi.encode(["address","address","address","address","address","int24","uint16","uint16", MS], ["0x000000000004444c5dc75cB358380D2e3dE08A90", engine, token, p.quote, account, p.initialTick, p.creatorBuyFeeBps, p.creatorSellFeeBps, p.modules])]);
console.log("hook initCode matches tx", ethers.keccak256(hookInit) === ethers.keccak256(hk.initCode));
const hook = ethers.getCreate2Address(GF, salt(nonce, h("hook"), hk.applicantSalt), ethers.keccak256(hookInit));
console.log("engine", engine, "token", token, "hook", hook);
console.log("expectedOutputs", route.expectedOutputs.map(o => o.account).join(" "));
console.log("hook flags", (BigInt(hook) & 16383n).toString(), "launchId ok", ethers.keccak256(abi.encode(["bytes32","bytes32","address"], [LID, nonce, token])) === sr.launchId);
console.log("stamped?", (await raw("eth_call", [{ to: ROUTER, data: ri.encodeFunctionData("launchIdByToken", [token]) }, "latest"])));
